### ISSUE TITLE
[Feature request]- Neural speed support

### ISSUE THREAD

**Issue by bil-ash** [mmomtchev/nobind#19]
There is an [LLM inference library](https://github.com/intel/neural-speed) by intel which allows low bits(2bits and higher) LLM inference on cpu. It also has [python binding](https://github.com/intel/neural-speed/tree/main/neural_speed/application) using pybind. Please generate nodejs bindings for the same using nobind (or maybe even SWIG).

**Comment by mmomtchev** [comment]
You think that you can post an issue simultaneously with someone else as part of an extortion involving the French police and corrupt judges and ask for a feature? Really?

**Comment by bil-ash** [comment]
Came here from your ffmpeg library, didn't read your history at that time. Read it now, feeling bad for you, life has already troubled you a lot, asking anything from you would be a sin. Sorry. May you have a better future ahead
